language: node_js
node_js:
    - "stable"
sudo: false
install:
    - npm install -g tslint tsd
    - npm install
    - tsd install
    - tslint --version
    - mkdir -p build/renderer
    - mkdir -p build/langpicker
script:
    - tslint $(git ls-files | grep '.ts$')
    - tsc -p browser/
    - tsc -p renderer/
    - tsc -p langpicker/
